name: Matrix the Ultimate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11', '17' ]
        
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Set up Java
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.1'
        java-version: '17'
        components: 'native-image'
          
    - name: Build with Maven
      run: mvn -B package --file pom.xml
